### ISSUE TITLE
Functions no longer work

### ISSUE THREAD

**Issue by panghy** [marcy-terui/gs-aws-pricing-helper#11]
It seems like many functions are no longer returning data (e.g. EC2_LINUX_RI_NO_HOUR, EBS_GP2_STORAGE, EBS_MAGNETIC_IO, etc.).

**Comment by Chhed13** [comment]
This https://github.com/marcy-terui/gs-aws-pricing-helper/pull/12 will fix some. There is no EBS_MAGNETIC_IO any more available

**Comment by yoavderazon** [comment]
hi @Chhed13 ,

just started using this, and it is great and can save a lot of work for me.
wondering if the issue wirth EBS_GPS and EC2_LINUX_RI* was merged, or planned to be merged in the near future.

**Comment by Chhed13** [comment]
Hi @yoavderazon ,
No, issue was not merge, @marcy-terui keeps silence. 
I do not keep an eye on hosting money any more, but that would be great to have this tool up to date.
